Remove --region flag for flyctl command
The --region flag has been removed and causes the deployment to fail
if it is specified.

```
+ flyctl deploy --config fly.toml --app sevensage-pr-1153 --region bos --image  --vm-memory 1024 --remote-only '--ha=false' --strategy immediate
Error: unknown flag: --region
```

Fly support say that if we specify primary_region in our fly.toml (which
we do), then we don't need to provide this flag which can have
unintended consequences.